server:
  port: 40000

spring:
  application:
    name: mall-cart
  session:
    store-type: redis
  redis:
    host: redis.cchu.me

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'