ipAddr: redis.cchu.me
server:
  port: 12000

spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
#ipAddr: 120.79.50.189


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
