spring:
  datasource:
    username: cchu
    password: cchucchu
    url: jdbc:mysql://mysql.cchu.me:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: rabiitmp.cchu.me
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: cchu
    password: cchucchu
    # 开启发送端确认
    publisher-confirms: true
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000


